// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CallDetails: typeof import('./src/components/call-details.vue')['default']
    Contacts: typeof import('./src/components/Contacts.vue')['default']
    IncomingCall: typeof import('./src/components/incoming-call.vue')['default']
    OutgoingCall: typeof import('./src/components/outgoing-call.vue')['default']
  }
}

export { }
